version: '3.8'

services:
  redis:
    image: redis
    container_name: cinema_cach
    expose:
      - 6379
  mongodb:
    build: ./mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'
  cinema:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
      - "81:81"
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    environment:
      - PORT=4000
      - REDIS_URL=redis
      - JWT_SECRET=helloworld
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/chat
    volumes:
      - ./uploads:/usr/cinema/uploads
      - ./hls:/usr/cinema/hls

volumes:
  uploads:
  hls:
  data:
  node_modules:
